/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelentlessRouteImport } from './routes/relentless'
import { Route as RadiantRouteImport } from './routes/radiant'
import { Route as PizzasquidRouteImport } from './routes/pizzasquid'
import { Route as KarmanRouteImport } from './routes/karman'
import { Route as IslandpopphotoRouteImport } from './routes/islandpopphoto'
import { Route as Errands99RouteImport } from './routes/errands99'
import { Route as EndlessworlddriverRouteImport } from './routes/endlessworlddriver'
import { Route as DrinkboxRouteImport } from './routes/drinkbox'
import { Route as CursedseasonsRouteImport } from './routes/cursedseasons'
import { Route as BotcrashRouteImport } from './routes/botcrash'
import { Route as AdriftamongthestarsRouteImport } from './routes/adriftamongthestars'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const RelentlessRoute = RelentlessRouteImport.update({
  id: '/relentless',
  path: '/relentless',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiantRoute = RadiantRouteImport.update({
  id: '/radiant',
  path: '/radiant',
  getParentRoute: () => rootRouteImport,
} as any)
const PizzasquidRoute = PizzasquidRouteImport.update({
  id: '/pizzasquid',
  path: '/pizzasquid',
  getParentRoute: () => rootRouteImport,
} as any)
const KarmanRoute = KarmanRouteImport.update({
  id: '/karman',
  path: '/karman',
  getParentRoute: () => rootRouteImport,
} as any)
const IslandpopphotoRoute = IslandpopphotoRouteImport.update({
  id: '/islandpopphoto',
  path: '/islandpopphoto',
  getParentRoute: () => rootRouteImport,
} as any)
const Errands99Route = Errands99RouteImport.update({
  id: '/errands99',
  path: '/errands99',
  getParentRoute: () => rootRouteImport,
} as any)
const EndlessworlddriverRoute = EndlessworlddriverRouteImport.update({
  id: '/endlessworlddriver',
  path: '/endlessworlddriver',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinkboxRoute = DrinkboxRouteImport.update({
  id: '/drinkbox',
  path: '/drinkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CursedseasonsRoute = CursedseasonsRouteImport.update({
  id: '/cursedseasons',
  path: '/cursedseasons',
  getParentRoute: () => rootRouteImport,
} as any)
const BotcrashRoute = BotcrashRouteImport.update({
  id: '/botcrash',
  path: '/botcrash',
  getParentRoute: () => rootRouteImport,
} as any)
const AdriftamongthestarsRoute = AdriftamongthestarsRouteImport.update({
  id: '/adriftamongthestars',
  path: '/adriftamongthestars',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adriftamongthestars': typeof AdriftamongthestarsRoute
  '/botcrash': typeof BotcrashRoute
  '/cursedseasons': typeof CursedseasonsRoute
  '/drinkbox': typeof DrinkboxRoute
  '/endlessworlddriver': typeof EndlessworlddriverRoute
  '/errands99': typeof Errands99Route
  '/islandpopphoto': typeof IslandpopphotoRoute
  '/karman': typeof KarmanRoute
  '/pizzasquid': typeof PizzasquidRoute
  '/radiant': typeof RadiantRoute
  '/relentless': typeof RelentlessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adriftamongthestars': typeof AdriftamongthestarsRoute
  '/botcrash': typeof BotcrashRoute
  '/cursedseasons': typeof CursedseasonsRoute
  '/drinkbox': typeof DrinkboxRoute
  '/endlessworlddriver': typeof EndlessworlddriverRoute
  '/errands99': typeof Errands99Route
  '/islandpopphoto': typeof IslandpopphotoRoute
  '/karman': typeof KarmanRoute
  '/pizzasquid': typeof PizzasquidRoute
  '/radiant': typeof RadiantRoute
  '/relentless': typeof RelentlessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adriftamongthestars': typeof AdriftamongthestarsRoute
  '/botcrash': typeof BotcrashRoute
  '/cursedseasons': typeof CursedseasonsRoute
  '/drinkbox': typeof DrinkboxRoute
  '/endlessworlddriver': typeof EndlessworlddriverRoute
  '/errands99': typeof Errands99Route
  '/islandpopphoto': typeof IslandpopphotoRoute
  '/karman': typeof KarmanRoute
  '/pizzasquid': typeof PizzasquidRoute
  '/radiant': typeof RadiantRoute
  '/relentless': typeof RelentlessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adriftamongthestars'
    | '/botcrash'
    | '/cursedseasons'
    | '/drinkbox'
    | '/endlessworlddriver'
    | '/errands99'
    | '/islandpopphoto'
    | '/karman'
    | '/pizzasquid'
    | '/radiant'
    | '/relentless'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adriftamongthestars'
    | '/botcrash'
    | '/cursedseasons'
    | '/drinkbox'
    | '/endlessworlddriver'
    | '/errands99'
    | '/islandpopphoto'
    | '/karman'
    | '/pizzasquid'
    | '/radiant'
    | '/relentless'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adriftamongthestars'
    | '/botcrash'
    | '/cursedseasons'
    | '/drinkbox'
    | '/endlessworlddriver'
    | '/errands99'
    | '/islandpopphoto'
    | '/karman'
    | '/pizzasquid'
    | '/radiant'
    | '/relentless'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdriftamongthestarsRoute: typeof AdriftamongthestarsRoute
  BotcrashRoute: typeof BotcrashRoute
  CursedseasonsRoute: typeof CursedseasonsRoute
  DrinkboxRoute: typeof DrinkboxRoute
  EndlessworlddriverRoute: typeof EndlessworlddriverRoute
  Errands99Route: typeof Errands99Route
  IslandpopphotoRoute: typeof IslandpopphotoRoute
  KarmanRoute: typeof KarmanRoute
  PizzasquidRoute: typeof PizzasquidRoute
  RadiantRoute: typeof RadiantRoute
  RelentlessRoute: typeof RelentlessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relentless': {
      id: '/relentless'
      path: '/relentless'
      fullPath: '/relentless'
      preLoaderRoute: typeof RelentlessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radiant': {
      id: '/radiant'
      path: '/radiant'
      fullPath: '/radiant'
      preLoaderRoute: typeof RadiantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pizzasquid': {
      id: '/pizzasquid'
      path: '/pizzasquid'
      fullPath: '/pizzasquid'
      preLoaderRoute: typeof PizzasquidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karman': {
      id: '/karman'
      path: '/karman'
      fullPath: '/karman'
      preLoaderRoute: typeof KarmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/islandpopphoto': {
      id: '/islandpopphoto'
      path: '/islandpopphoto'
      fullPath: '/islandpopphoto'
      preLoaderRoute: typeof IslandpopphotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errands99': {
      id: '/errands99'
      path: '/errands99'
      fullPath: '/errands99'
      preLoaderRoute: typeof Errands99RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endlessworlddriver': {
      id: '/endlessworlddriver'
      path: '/endlessworlddriver'
      fullPath: '/endlessworlddriver'
      preLoaderRoute: typeof EndlessworlddriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinkbox': {
      id: '/drinkbox'
      path: '/drinkbox'
      fullPath: '/drinkbox'
      preLoaderRoute: typeof DrinkboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursedseasons': {
      id: '/cursedseasons'
      path: '/cursedseasons'
      fullPath: '/cursedseasons'
      preLoaderRoute: typeof CursedseasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/botcrash': {
      id: '/botcrash'
      path: '/botcrash'
      fullPath: '/botcrash'
      preLoaderRoute: typeof BotcrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adriftamongthestars': {
      id: '/adriftamongthestars'
      path: '/adriftamongthestars'
      fullPath: '/adriftamongthestars'
      preLoaderRoute: typeof AdriftamongthestarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdriftamongthestarsRoute: AdriftamongthestarsRoute,
  BotcrashRoute: BotcrashRoute,
  CursedseasonsRoute: CursedseasonsRoute,
  DrinkboxRoute: DrinkboxRoute,
  EndlessworlddriverRoute: EndlessworlddriverRoute,
  Errands99Route: Errands99Route,
  IslandpopphotoRoute: IslandpopphotoRoute,
  KarmanRoute: KarmanRoute,
  PizzasquidRoute: PizzasquidRoute,
  RadiantRoute: RadiantRoute,
  RelentlessRoute: RelentlessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
